modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Dplayend/Just-Potion-Rings/issues"
[[mods]]
modId="justpotionrings"
version="1.3"
displayName="Just Potion Rings"
authors="Dplayend"
description='''
Adds Rings that apply potion effects to the player while worn.
'''
displayURL="https://www.curseforge.com/minecraft/mc-mods/just-potion-rings"
logoFile="icon.png"
